baseURL = 'https://lprekon.github.io/'
languageCode = 'en-us'
title = 'CodeFarming'
theme = 'paige'
markup.goldmark.renderer.unsafe = true
enableRobotsTXT = true

[params.paige]
style = """
#paige-page-content > * {
margin-left: auto;
margin-right: auto;
# max-width: 40rem;
}

:root {
  /* Base font size - applies to smaller screens by default */
  font-size: 16px;
}

/* Medium screens */
@media (min-width: 768px) {
  :root {
    font-size: 17px;
  }
}

/* Large screens */
@media (min-width: 1200px) {
  :root {
    font-size: 18px;
  }
}

/* Extra large screens */
@media (min-width: 1600px) {
  :root {
    font-size: 22px;
  }
}

/* Allow images to be wider */
/* Special case for paragraphs that contain only images */
#paige-page-content > p:has(> img:only-child),
#paige-page-content > figure,
#paige-page-content > figure.image-row-container {
  # max-width: 60rem; /* Wider max-width for images and figures */
}

#paige-page-content > p > img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  margin-top: 1.5rem;    /* Adds space above the image */
  margin-bottom: 1.5rem; /* Adds space below the image */
  max-width: 100%;
  height: auto;
}
"""
[params.paige.site]
color = '#2b2b2b'

[params.paige.pages]
disable_authors = true
disable_reading_time = true
disable_word_count = true
